=jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Specify the version of Node.js

      - name: Install, Build, and Test
        run: |
          npm install
          npm run build --if-present
          npm test

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .
